version: "3"

services:
  dynamodblocal:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -port 8000 -dbPath ./data -sharedDb"
    volumes:
      - "./dynamoDB/data:/home/dynamodblocal/data"
    networks:
      - dynamodb
    ports:
      - 8000:8000

  python3:
    container_name: python
    build:
      context: "."
      dockerfile: "Dockerfile"
    tty: true
    volumes:
        - "./dynamoDB/script:/root"
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000/
    networks:
      - dynamodb

  dynamodbadmin:
    image: instructure/dynamo-local-admin
    networks:
      - dynamodb
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000/

networks:
  dynamodb:
    driver: "bridge"