version: "3"

services:
  dynamodblocal:
    container_name: dynamodb
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -port 8000 -dbPath ./data -sharedDb"
    volumes:
      - "./dynamoDB:/home/dynamodblocal/data" 
    networks:
      - default
    ports:
      - 8000:8000
      
  dynamodbadmin:
    image: instructure/dynamo-local-admin
    networks:
      - default
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000/