AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 5

Resources:
  # リソース名
  LambdaSampleFunction:
    # リソース種別(Lambdaはこの書き方)
    Type: AWS::Serverless::Function
    Properties:
      # 成果物のパス(ディレクトリまで)
      CodeUri: "./lambdaSample/"
      # ハンドラー
      Handler: main
      # Runtime
      Runtime: go1.x
      # 環境変数セット
      Environment:
        Variables:
          DB_TYPE: 
          POSTGRES_DBHOST: 
          POSTGRES_DBNAME: 
          POSTGRES_DBUSER: 
          POSTGRES_PASSWORD: 
      Events:
        # この設定だけでAPIgetewayが自動生成される
        Api:
            Type: Api
            Properties:
                Path: /area/{zipCode}
                Method: get
  # リソース名
  TriggerBySNSFunction:
    # リソース種別(Lambdaはこの書き方)
    Type: AWS::Serverless::Function
    Properties:
      # 成果物のパス(ディレクトリまで)
      CodeUri: "./triggerSNS/"
      # ハンドラー
      Handler: main
      # Runtime
      Runtime: go1.x
      # 環境変数セット

Outputs:
  LambdaSampleFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt LambdaSampleFunction.Arn
  LambdaSampleIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaSampleFunctionRole.Arn
