AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  blog

  Sample SAM Template for blog

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  blogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  blogLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blog/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        getBlogs:
          Type: Api
          Properties:
            Path: /blogs  
            Method: get
            RestApiId: !Ref blogApi
        getBlog:
          Type: Api
          Properties:
            Path: /blog/{id}
            Method: get
            RestApiId: !Ref blogApi
        postBlog:
          Type: Api
          Properties:
            Path: /blog
            Method: post
            RestApiId: !Ref blogApi
        putBlog:
          Type: Api
          Properties:
            Path: /blog/{id}
            Method: put
            RestApiId: !Ref blogApi
        deleteBlog:
          Type: Api
          Properties:
            Path: /blog/{id}
            Method: delete
            RestApiId: !Ref blogApi
